import {
  House1,
  House2,
  House3,
  House4,
  House5,
  House6,
  House7,
  House8,
  Office1,
  Office2,
  Office3,
  Office4,
  Office5,
  Office6,
  Villa1,
  Villa2,
  Villa3,
  Villa4,
  Villa5,
  Villa6,
  Villa7,
} from "../assets";

export const properties = [
  {
    id: 1,
    title: "A stunning waterfront home near the marina",
    location: "23 Admiralty Way, Lekki",
    images: [House1, House2, House3, House4],
    category: "smart house",
    type: "Rent",
    price: "1000000",
  },
  {
    id: 2,
    title: "Elegant villa steps from the luxury district.",
    location: "15 Awolowo Road, Ikoyi",
    images: [Villa1, Villa2, Villa3, Villa4],
    category: "villa",
    type: "Sale",
    price: "720000000",
  },
  {
    id: 3,
    title: "Sleek office  in the heart of Victoria Island.",
    location: "12 Adeola Odeku Street, VI",
    images: [Office2, Office1, Office4, Office3],
    category: "office",
    type: "Lease",
    price: "1500000",
  },
  {
    id: 4,
    title: "Modern apartment close to business hubs.",
    location: "9 Freedom Drive, Victoria Island",
    images: [House8, House5, House4, House7],
    category: "apartment",
    type: "Rent",
    price: "2500000",
  },
  {
    id: 5,
    title: "Spacious bungalow near top-rated schools.",
    location: "7 Isaac John Street, Ikeja GRA",
    images: [Villa7, Villa5, Villa6, Villa4],
    category: "bungalow",
    type: "Sale",
    price: "6000000000",
  },
  {
    id: 6,
    title: "Modern apartment close to business hubs.",
    location: "18 Ogo-Oluwa Street, Osogbo",
    images: [House4, House6, House1, House5],
    category: "smart home",
    type: "Sale",
    price: "90000000",
  },
  {
    id: 7,
    title: "Spacious office space near major roadways",
    location: "Marina, Lagos",
    images: [Office3, Office5, Office6, Office1],
    category: "office",
    type: "Rent",
    price: "70000000",
  },
  {
    id: 8,
    title: "Well-finished villa close to cultural landmarks.",
    location: "Banana Island, Lagos",
    images: [Villa6, Villa2, Villa1, Villa5],
    category: "villa",
    type: "Lease",
    price: "78000000",
  },
  {
    id: 9,
    title: "Urban Apartment",
    location: "Surulere, Lagos",
    images: [House3, House6, House1, House4],
    category: "apartment",
    type: "Sale",
    price: "3500000",
  },
  {
    id: 10,
    title: "Bungalow with Private Pool",
    location: "Ikoyi, Lagos",
    images: [House2, House8, House6, House4],
    category: "bungalow",
    type: "For Lease",
    price: "50000000",
  },
];
